Repository CS2103JAN2018-W11-B4/main, pull requests merged in 2018-03, with the labels that each got.

#24 Add Birthday Parameter to Person Class
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: can.merge

#55 Customised Password System
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/PasswordCorrectEvent.java
  src/main/java/seedu/address/commons/exceptions/WrongPasswordException.java
  src/main/java/seedu/address/commons/util/SecurityUtil.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AliasCommandParser.java
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Password.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/SecurityUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedPassword.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/PasswordBox.java
  src/main/java/seedu/address/ui/PasswordUiManager.java
  src/main/java/seedu/address/ui/PasswordWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/PasswordBox.fxml
  src/main/resources/view/PasswordWindow.fxml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/util/SecurityUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/PasswordCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/SecurityUtilTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
Labels: can.merge

#73 Add Birthdays Command
  src/main/java/seedu/address/commons/events/ui/BirthdayListEvent.java
  src/main/java/seedu/address/logic/commands/BirthdaysCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/BirthdayList.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BirthdayList.fxml
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/ui/BrowserPanelTest.java
Labels: can.merge

#72 Add password support for import command
  .gitignore
  src/main/java/seedu/address/commons/util/SecurityUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/test/data/ImportCommandTest/aliceBensonAddressBook.xml
  src/test/data/ImportCommandTest/encryptedAliceBensonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/TempEncryptedAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PasswordCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
Labels: do.not.merge

#81 Add Storage and Model Components of VacantRoomFinder Feature
  config.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/VacantCommand.java
  src/main/java/seedu/address/logic/parser/VacantCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/building/Building.java
  src/main/java/seedu/address/model/building/Room.java
  src/main/java/seedu/address/model/building/Week.java
  src/main/java/seedu/address/model/building/WeekDay.java
  src/main/java/seedu/address/model/building/exceptions/BuildingNotFoundException.java
  src/main/java/seedu/address/storage/ReadOnlyJsonVenueInformation.java
  src/main/java/seedu/address/storage/ReadOnlyVenueInformation.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  venueinformation.json
Labels: can.merge

#79 Update Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentPasswordSequenceDiagram.pptx
  docs/images/PasswordSdForLogic.png
  docs/images/PasswordSdForModel.png
  docs/images/azureair.jpg
Labels: can.merge

#85 Fix clear alias bug
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/UnaliasCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/alias/UniqueAliasList.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: can.merge

#86 Update Documentation for Birthdays
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/LogicComponentBirthdaysSequenceDiagram.pptx
  docs/diagrams/UiComponentBirthdayListSequenceDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/LogicComponentBirthdaysSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiComponentBirthdayListSequenceDiagram.png
Labels: can.merge

#87 Update design considerations for alias
  docs/DeveloperGuide.adoc
Labels: can.merge

#104 Update user guide
  docs/UserGuide.adoc
Labels: can.merge

#105 Changing all instance of address book
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
Labels: can.merge

#106 Update Tests for Encryption
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
Labels: can.merge

#107 Addition of more Test for Password UI
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/XmlAdaptedPassword.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/PasswordBox.java
  src/main/java/seedu/address/ui/PasswordWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PasswordBox.fxml
  src/main/resources/view/PasswordWindow.fxml
  src/test/data/PasswordBoxTest/encryptedAddressBook.xml
  src/test/java/guitests/guihandles/PasswordBoxHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPasswordTest.java
  src/test/java/seedu/address/ui/PasswordBoxTest.java
Labels: can.merge

#108 Alias tests
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/main/java/seedu/address/logic/parser/AliasCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/alias/Alias.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/parser/AliasCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/testutil/AliasBuilder.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: can.merge

#109 Disable Encryption System
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/SecurityUtil.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/logic/commands/RemovePasswordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemovePasswordCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Password.java
  src/main/java/seedu/address/storage/XmlAdaptedPassword.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/RemovePasswordCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PasswordCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemovePasswordCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/ui/PasswordBoxTest.java
Labels: do.not.merge, type.enhancement

#111 Vacant room UI
  src/main/java/seedu/address/commons/events/ui/VenueTableEvent.java
  src/main/java/seedu/address/logic/commands/VacantCommand.java
  src/main/java/seedu/address/model/building/Room.java
  src/main/java/seedu/address/model/building/Week.java
  src/main/java/seedu/address/model/building/WeekDay.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/VenueTable.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/VenueTable.fxml
  src/test/data/XmlAddressBookStorageTest/TempEncryptedAddressBook.xml
  src/test/java/seedu/address/logic/commands/VacantCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/VacantCommandParserTest.java
Labels: can.merge

#116 Update Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: can.merge

#127 Add alias model and unique alias list tests
  src/main/java/seedu/address/model/alias/UniqueAliasList.java
  src/main/java/seedu/address/model/alias/exceptions/DuplicateAliasException.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/UniqueAliasListTest.java
  src/test/java/seedu/address/model/alias/AliasTest.java
Labels: can.merge
