Repository CS2103JAN2018-W11-B4/main, pull requests merged in 2018-04, with the labels that each got.

#131 Add test cases for VacantRoomFinder feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/building/Building.java
  src/main/java/seedu/address/model/building/Room.java
  src/main/java/seedu/address/model/building/Week.java
  src/main/java/seedu/address/model/building/WeekDay.java
  src/test/java/seedu/address/model/building/BuildingTest.java
  src/test/java/seedu/address/model/building/RoomTest.java
  src/test/java/seedu/address/model/building/WeekDayTest.java
  src/test/java/seedu/address/model/building/WeekTest.java
  src/test/java/seedu/address/storage/ReadOnlyJsonVenueInformationTest.java
  src/test/java/seedu/address/testutil/BuildingBuilder.java
  src/test/java/seedu/address/testutil/RoomBuilder.java
  src/test/java/seedu/address/testutil/WeekBuilder.java
  src/test/java/seedu/address/testutil/WeekDayBuilder.java
  src/test/resources/ReadOnlyJsonVenueInformationTest/EmptyVenueInformation.json
  src/test/resources/ReadOnlyJsonVenueInformationTest/ExtraValuesVenueInformation.json
  src/test/resources/ReadOnlyJsonVenueInformationTest/NotJsonFormatVenueInformation.json
  src/test/resources/ReadOnlyJsonVenueInformationTest/TypicalVenueInformation.json
Labels: can.merge

#132 Collate
  collated/functional/jingyinno.md
  collated/test/jingyinno.md
  src/main/java/seedu/address/commons/events/ui/VenueTableEvent.java
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/main/java/seedu/address/logic/commands/UnaliasCommand.java
  src/main/java/seedu/address/logic/commands/VacantCommand.java
  src/main/java/seedu/address/logic/parser/AliasCommandParser.java
  src/main/java/seedu/address/logic/parser/UnaliasCommandParser.java
  src/main/java/seedu/address/logic/parser/VacantCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/alias/Alias.java
  src/main/java/seedu/address/model/alias/UniqueAliasList.java
  src/main/java/seedu/address/model/alias/exceptions/AliasNotFoundException.java
  src/main/java/seedu/address/model/alias/exceptions/DuplicateAliasException.java
  src/main/java/seedu/address/storage/XmlAdaptedAlias.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/VenueTable.java
  src/main/resources/view/VenueTable.fxml
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UnaliasCommandTest.java
  src/test/java/seedu/address/logic/commands/VacantCommandTest.java
  src/test/java/seedu/address/logic/parser/AliasCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UnaliasCommandParserTest.java
  src/test/java/seedu/address/logic/parser/VacantCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/UniqueAliasListTest.java
  src/test/java/seedu/address/model/alias/AliasTest.java
  src/test/java/seedu/address/testutil/AliasBuilder.java
  src/test/java/seedu/address/testutil/AliasUtil.java
  src/test/java/seedu/address/testutil/TypicalAliases.java
Labels: can.merge

#134 Collate all files modified by Caijun7
  collated/functional/Caijun7-reused.md
  collated/functional/Caijun7.md
  collated/test/Caijun7-reused.md
  collated/test/Caijun7.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/building/Building.java
  src/main/java/seedu/address/model/building/Room.java
  src/main/java/seedu/address/model/building/Week.java
  src/main/java/seedu/address/model/building/WeekDay.java
  src/main/java/seedu/address/model/building/exceptions/BuildingNotFoundException.java
  src/main/java/seedu/address/model/building/exceptions/CorruptedVenueInformationException.java
  src/main/java/seedu/address/model/building/exceptions/InvalidWeekDayScheduleException.java
  src/main/java/seedu/address/model/building/exceptions/InvalidWeekScheduleException.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/storage/ReadOnlyJsonVenueInformation.java
  src/main/java/seedu/address/storage/ReadOnlyVenueInformation.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/data/ImportCommandTest/aliceAddressBook.xml
  src/test/data/ImportCommandTest/aliceBensonAddressBook.xml
  src/test/data/ImportCommandTest/bensonAddressBook.xml
  src/test/data/ImportCommandTest/invalidFileFormatAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/validAddressBook.xml
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/building/BuildingTest.java
  src/test/java/seedu/address/model/building/RoomTest.java
  src/test/java/seedu/address/model/building/WeekDayTest.java
  src/test/java/seedu/address/model/building/WeekTest.java
  src/test/java/seedu/address/storage/ReadOnlyJsonVenueInformationTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/BuildingBuilder.java
  src/test/java/seedu/address/testutil/RoomBuilder.java
  src/test/java/seedu/address/testutil/WeekBuilder.java
  src/test/java/seedu/address/testutil/WeekDayBuilder.java
Labels: can.merge

#140 Add Collated code
  collated/functional/jingyinno.md
  collated/functional/yeggasd-reused.md
  collated/functional/yeggasd.md
  collated/test/Caijun7.md
  collated/test/jingyinno.md
  collated/test/yeggasd.md
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/events/ui/PasswordCorrectEvent.java
  src/main/java/seedu/address/commons/exceptions/WrongPasswordException.java
  src/main/java/seedu/address/commons/util/SecurityUtil.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/logic/commands/RemovePasswordCommand.java
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
  src/main/java/seedu/address/logic/parser/RemovePasswordCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Password.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/storage/XmlAdaptedPassword.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/ui/PasswordBox.java
  src/main/java/seedu/address/ui/PasswordUiManager.java
  src/main/java/seedu/address/ui/PasswordWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PasswordBox.fxml
  src/main/resources/view/PasswordWindow.fxml
  src/test/data/XmlAddressBookStorageTest/TempEncryptedAddressBook.xml
  src/test/java/guitests/guihandles/PasswordBoxHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/SecurityUtilTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/PasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/RemovePasswordCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PasswordCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemovePasswordCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPasswordTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/ui/PasswordBoxTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: can.merge, type.task

#135 Add Export Command Feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/UnaliasCommandTest.java
  src/test/java/seedu/address/logic/commands/VacantCommandTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
Labels: can.merge

#145 Add Auto Resize and Disable reordering for VenueTable
  src/main/java/seedu/address/ui/VenueTable.java
Labels: can.merge

#151 Collate Code
  collated/functional/AzuraAiR-reused.md
  collated/functional/AzuraAiR.md
  collated/test/AzuraAiR.md
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/BirthdayListEvent.java
  src/main/java/seedu/address/commons/events/ui/BirthdayNotificationEvent.java
  src/main/java/seedu/address/commons/exceptions/NoInternetConnectionException.java
  src/main/java/seedu/address/commons/util/timetable/Lesson.java
  src/main/java/seedu/address/commons/util/timetable/TimetableParserUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BirthdaysCommand.java
  src/main/java/seedu/address/logic/parser/BirthdaysCommandParser.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/timetable/Timetable.java
  src/main/java/seedu/address/model/person/timetable/TimetableData.java
  src/main/java/seedu/address/model/person/timetable/TimetableDay.java
  src/main/java/seedu/address/model/person/timetable/TimetableSlot.java
  src/main/java/seedu/address/model/person/timetable/TimetableWeek.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/ui/BirthdayList.java
  src/main/java/seedu/address/ui/BirthdayNotification.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/resources/view/BirthdayList.fxml
  src/test/java/guitests/guihandles/BirthdayListHandle.java
  src/test/java/guitests/guihandles/BirthdayNotificationHandle.java
  src/test/java/seedu/address/logic/commands/BirthdaysCommandTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/testutil/TimetableBuilder.java
  src/test/java/seedu/address/ui/BirthdayListTest.java
  src/test/java/systemtests/BirthdaysCommandSystemTest.java
Labels: priority.high

#147 Add maps feature
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/GoogleMapsEvent.java
  src/main/java/seedu/address/logic/commands/MapCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MapCommandParser.java
  src/main/java/seedu/address/model/building/Building.java
  src/main/java/seedu/address/ui/GoogleMapsDisplay.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/resources/view/GoogleMapsDisplay.fxml
  src/main/resources/view/InfoPanel.fxml
Labels: can.merge

#154 Update alias for new commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AliasCommand.java
Labels: can.merge

#156 Collate
  collated/functional/AzuraAiR-reused.md
  collated/functional/AzuraAiR.md
  collated/functional/Caijun7-reused.md
  collated/functional/Caijun7.md
  collated/functional/jingyinno.md
  collated/functional/yeggasd-reused.md
  collated/functional/yeggasd.md
  collated/test/AzuraAiR.md
  collated/test/Caijun7-reused.md
  collated/test/Caijun7.md
  collated/test/jingyinno.md
  collated/test/yeggasd.md
  src/main/java/seedu/address/commons/events/ui/GoogleMapsEvent.java
  src/main/java/seedu/address/logic/commands/MapCommand.java
  src/main/java/seedu/address/logic/parser/MapCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/GoogleMapsDisplay.java
  src/main/resources/view/GoogleMapsDisplay.fxml
Labels: can.merge

#155 Update User and Developer Guide for Vacant Room Finder
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
Labels: can.merge

#160 Update Collate and Fix Typo
  collated/functional/AzuraAiR-reused.md
  collated/functional/AzuraAiR.md
  collated/functional/Caijun7-reused.md
  collated/functional/Caijun7.md
  collated/functional/jingyinno.md
  collated/functional/yeggasd-reused.md
  collated/functional/yeggasd.md
  src/main/java/seedu/address/ui/InfoPanel.java
Labels: type.task

#166 Fix bug due to no rooms in building
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/VacantCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/building/Building.java
  src/main/java/seedu/address/model/building/exceptions/NoRoomsInBuildingException.java
  src/test/java/seedu/address/model/building/BuildingTest.java
Labels: priority.high

#168 Fix Timetable message in App
  src/main/java/seedu/address/logic/commands/TimeTableCommand.java
Labels: can.merge

#167 Alias storage test and enhance parser
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/main/java/seedu/address/logic/parser/AliasCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/alias/Alias.java
  src/main/java/seedu/address/model/alias/UniqueAliasList.java
  src/main/java/seedu/address/storage/XmlAdaptedAlias.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AliasCommandTest.java
  src/test/java/seedu/address/logic/commands/UnaliasCommandTest.java
  src/test/java/seedu/address/logic/commands/VacantCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/alias/AliasTest.java
  src/test/java/seedu/address/storage/XmlAdaptedAliasTest.java
  src/test/java/seedu/address/testutil/TypicalAliases.java
Labels: can.merge

#165 Add more Timetable Test
  src/main/java/seedu/address/model/person/timetable/Timetable.java
  src/main/java/seedu/address/model/person/timetable/TimetableDay.java
  src/main/java/seedu/address/model/person/timetable/TimetableWeek.java
  src/test/java/seedu/address/commons/util/TimetableParserUtilTest.java
  src/test/java/seedu/address/model/person/TimetableTest.java
Labels: do.not.merge, status.ongoing

#203 Update user guide
  docs/UserGuide.adoc
  docs/images/birthdaysToday.png
  docs/images/map.png
  docs/images/timetable.png
  docs/images/vacant.png
Labels: can.merge

#204 Fix Timetable bugs
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/timetable/Timetable.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: do.not.merge

#191 Fix bug due to null password
  src/main/java/seedu/address/commons/util/SecurityUtil.java
Labels: can.merge, priority.high

#162 Add PersonDetailsPanel
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/JumpToListRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/PersonPanelSelectionChangedEvent.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/GoogleMapsDisplay.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/PersonDetailsCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TimeTablePanel.java
  src/main/java/seedu/address/ui/VenueTable.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/PersonDetailsCard.fxml
  src/main/resources/view/TimeTablePanel.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalOddEven.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  unused/TimeTableCommand.java
  unused/TimeTableCommandParser.java
  unused/TimeTableCommandParserTest.java
  unused/TimeTableCommandTest.java
Labels: can.merge, status.ongoing, type.enhancement

#214 Documentation
  docs/UserGuide.adoc
  docs/team/yeggasd.adoc
Labels: can.merge, type.task

#212 Administrative
  src/main/java/seedu/address/commons/util/SecurityUtil.java
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
  src/main/java/seedu/address/logic/parser/RemovePasswordCommandParser.java
  src/main/java/seedu/address/ui/PasswordBox.java
  src/main/resources/view/PasswordWindow.fxml
Labels: can.merge, type.task

#213 Change documentation of AddressBook to StardyTogether
  src/main/java/seedu/address/logic/commands/ImportCommand.java
Labels: can.merge

#216 Add Project Portfolio of Caijun7
  collated/functional/Caijun7-reused.md
  collated/functional/Caijun7.md
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Caijun7.adoc
Labels: can.merge

#215 Changing PasswordCommand and RemovePasswordCommand Command word
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/logic/commands/RemovePasswordCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AliasCommandParserTest.java
Labels: can.merge, type.task

#221 Update Doc
  docs/AboutUs.adoc
  docs/team/yeggasd.adoc
Labels: can.merge

#223 Update Collate
  collated/functional/jingyinno.md
  collated/functional/yeggasd.md
  collated/test/Caijun7-reused.md
  collated/test/Caijun7.md
  collated/test/jingyinno.md
  collated/test/yeggasd.md
  collated/unused/yeggasd-unused.md
Labels: can.merge

#230 Add test cases for Export command
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/UploadCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/CancellableServerReceiver.java
  src/main/java/seedu/address/storage/GoogleDriveStorage.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/test/data/ExportCommandTest/aliceAddressBook.xml
  src/test/data/ExportCommandTest/aliceBensonAddressBook.xml
  src/test/data/GoogleDriveStorageTest/validAddressBook.xml
  src/test/data/UploadCommandTest/aliceAddressBook.xml
  src/test/data/UploadCommandTest/aliceBensonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/aliceBensonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/encryptedAliceBensonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/encryptedAliceBensonAddressBookBackup.xml
  src/test/data/XmlSerializableAddressBookTest/invalidAliasAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalAliasesAddressBook.xml
  src/test/java/guitests/guihandles/AliasListHandle.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/UploadCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UploadCommandParserTest.java
  src/test/java/seedu/address/model/UniquePersonListTest.java
  src/test/java/seedu/address/model/UniqueTagListTest.java
  src/test/java/seedu/address/storage/GoogleDriveStorageTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalAliases.java
  src/test/java/systemtests/ExportCommandSystemTest.java
  src/test/java/systemtests/ImportCommandSystemTest.java
  src/test/java/systemtests/UploadCommandSystemTest.java
  src/test/java/systemtests/VacantCommandSystemTest.java
  src/test/resources/GoogleCredentials/StoredCredential
Labels: do.not.merge, priority.high

#234 Improve Code quality
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/BirthdayListEvent.java
  src/main/java/seedu/address/commons/events/ui/BirthdayNotificationEvent.java
  src/main/java/seedu/address/commons/events/ui/TimeTableEvent.java
  src/main/java/seedu/address/commons/util/timetable/TimetableParserUtil.java
  src/main/java/seedu/address/logic/commands/BirthdaysCommand.java
  src/main/java/seedu/address/logic/commands/TimetableUnionCommand.java
  src/main/java/seedu/address/model/person/timetable/TimetableWeek.java
  src/main/java/seedu/address/ui/BirthdayList.java
  src/main/java/seedu/address/ui/BirthdayNotification.java
  src/main/java/seedu/address/ui/PasswordUiManager.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BirthdayList.fxml
  src/test/java/guitests/guihandles/BirthdayNotificationHandle.java
  src/test/java/seedu/address/model/person/TimetableTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/BirthdaysCommandSystemTest.java
Labels: can.merge

#235 Update DeveloperGuide and UserGuide
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicComponentPasswordSequenceDiagram.pptx
  docs/diagrams/ModelComponentPasswordSequenceDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/PasswordSdForLogic.png
  docs/images/PasswordSdForModel.png
  docs/images/StorageClassDiagram.png
  docs/images/wrongPasswordDialog.PNG
Labels: can.merge

#232 Update user and developer guide
  collated/functional/Caijun7-reused.md
  collated/functional/Caijun7.md
  collated/test/Caijun7.md
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/UploadCommand.java
Labels: do.not.merge, priority.high

#237 Developer guide update
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicComponentImportSequenceDiagram.pptx
  docs/images/LogicComponentImportSequenceDiagram.png
Labels: priority.high

#238 Update tests and documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AliasCommand.java
  src/main/java/seedu/address/logic/commands/MapCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/alias/UniqueAliasList.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MapCommandTest.java
  src/test/java/seedu/address/logic/parser/AliasCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/UniqueAliasListTest.java
  src/test/java/seedu/address/model/alias/AliasTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalAliases.java
  src/test/java/seedu/address/ui/AliasListTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/AliasCommandSystemTest.java
  src/test/java/systemtests/BirthdaysCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/UnaliasCommandSystemTest.java
Labels: do.not.merge

#247 Update DG and PPP
  docs/DeveloperGuide.adoc
  docs/diagrams/AutoCorrectDiagram.pptx
  docs/images/commandautocomplete.png
  docs/images/commandautocorrect.png
  docs/images/parameterautocomplete.png
  docs/team/yeggasd.adoc
Labels: can.merge

#249 Final collate
  collated/functional/AzuraAiR-reused.md
  collated/functional/AzuraAiR.md
  collated/functional/Caijun7-reused.md
  collated/functional/Caijun7.md
  collated/functional/jingyinno.md
  collated/functional/yeggasd-reused.md
  collated/functional/yeggasd.md
  collated/test/AzuraAiR.md
  collated/test/Caijun7-reused.md
  collated/test/Caijun7.md
  collated/test/jingyinno.md
  collated/test/yeggasd.md
  collated/unused/yeggasd-unused.md
Labels: priority.high
